apiVersion: v1
kind: Service
metadata:
  name: cafeteria-metrics
  namespace: default
  labels:
    app: cafeteria
    component: metrics
spec:
  selector:
    app: cafeteria

  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP

  type: ClusterIP
