apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeteria-deployment
  labels:
    app: cafeteria

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cafeteria

  template:
    metadata:
      labels:
        app: cafeteria

    spec:
      containers:
        - name: cafeteria
          image: ronal29/cafeteria:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20