apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeteria-deployment
  namespace: default
  labels:
    app: cafeteria

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cafeteria

  template:
    metadata:
      labels:
        app: cafeteria

    spec:
      containers:
        - name: cafeteria
          image: ronal29/cafeteria:2e47f7cc4530a48c86bd0a5fa61d9a7e7d9ce679
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20