name: CI - Cafeteria React

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Descargar codigo
        uses: actions/checkout@v7

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: npm ci

      # 4. Ejecutar pruebas
      - name: Ejecutar pruebas
        run: npm test -- --watchAll=false

      # 5. Construir aplicación React
      - name: Construir aplicacion
        run: npm run build

      # 6. Construir imagen Docker
      - name: Construir imagen Docker
        run: docker build -t cafeteria:${{ github.sha }} .